### ISSUE TITLE
Alternative method to enter minutes / seconds.

### ISSUE THREAD

**Issue by supertorpe** [micrusa/AmazTimer#11]
Currently, the way to increase or decrease the time values using the + and - symbols, adds or subtracts 1 second each time.
If you want to configure minute intervals, this method becomes unfeasible. Could an alternative method be implemented to configure the minutes / seconds? Maybe a long press on the + could fast-forward the values; Or maybe create an editor where you can move minutes or seconds separately.

**Comment by micrusa** [comment]
I'm currently working on tcx exports, I will add a long press to increase/decrease them faster soon

**Comment by micrusa** [comment]
Done, now long clicks will increase 1m instead of 1s
