### ISSUE TITLE
Croatian strings

### ISSUE THREAD

**Issue by MASVA** [micrusa/AmazTimer#3]
<string name="start">Start</string>
    <string name="work">Rad</string>
    <string name="rest">Odmor</string>
    <string name="sets" translatable="false">Setovi</string>
    <string name="prepare">Pripremite se!</string>
    <string name="cancel">Odustani</string>
    <string name="canceltoast">Dugi klik!</string>
    <string name="settings">Postavke</string>
    <string name="batterysaving">Štednja baterije</string>
    <string name="lang">Jezik</string>
    <string name="startsettings">Dugo pritisnite Sttart za postavke</string>
    <string name="hrEnabled">Praćenje rada srca</string>

**Comment by micrusa** [comment]
Thanks, will be added in next release
