### ISSUE TITLE
Error in settings screen after upgrading to 4.2

### ISSUE THREAD

**Issue by supertorpe** [micrusa/AmazTimer#9]
I have uninstalled version 4.1 before installing version 4.2. When trying to access the settings screen, the app crashed and exits. I have had to clean the application data to avoid the error:
adb shell pm clear me.micrusa.amaztimer

**Comment by micrusa** [comment]
I didn't have any problem uninstalling and installing, but there might be problems when installing it over 4.1 because I used the same key for age and weight after changing type of preference, so I added a note to the release. Thanks :)
